experiment_name: gan_cinn_hsi


n_blocks: 40
n_conditional_blocks: 30
clamping: 1.0
actnorm: .7
n_reflections: 0
n_hidden: 512
ndim_x: 16


test_run: True
epochs: 300
seed: 42

batch_size: 10000
num_workers: 16
shuffle: 1
learning_rate: 0.0001

adversarial_training: 1
gan_weight: 1
ml_weight: 1
recon_criterion: mse        # mse or abs
noise_aug: True
noise_aug_level: 0.1
normalization: standardize    # min_max or standardize
instant_downsampling: False
weight_decay: 0.0001           # weight decay
beta1: 0.9                    # Adam parameter
beta2: 0.95
condition: segmentation       # segmentation, domain, both
label_noise: True
label_noise_level: 0.5
real_labels: random_choice

data:
  data_set_name: real_sim_hsi     # real_sim, sim or mnist_usps
  dataset_version: semantic_v2    # semantic or semantic_v2
  data_dir_a: test_dir_a
  data_dir_b: test_dir_b
  used_channels: 16          # int as index of list [700, 855, 10] or list of int as indices, e.g. [0, 3, 6, 15]
  log: False                 # indicate if data have been taken logarithmic
  balance_classes: True
  choose_spectra: unique      # unique or sampled

dis:
  dim: 256                     # number of filters in the bottommost layer
  activation: lrelu                # activation function [relu/lrelu/prelu/selu/tanh]
  n_layer: 3                  # number of layers in D
  gan_type: lsgan             # GAN loss [lsgan/nsgan]
  dropout: True
  dropout_p: 0.2
